### PR TITLE
Updates docs and `example/` folder

### PR DESCRIPTION
**Pull request by NoeSamaille**
- Prettify docs and added required `Allow group terraform-group to manage dynamic-groups in tenancy` policy statement for zero trust install.
- Updated `example/` folder with required variables.

### CODE REVIEW

**Comment by NoeSamaille** [comment]
@garutilorenzo FYI for approval and merge

**Comment by garutilorenzo** [comment]
Wonderful @NoeSamaille thank you so much 😃

**Comment by liviux** [comment]
So this changed since yesterday and crashed my test. Now i don't manage to understand which public_key_path is needed. Is the same created for OCI? like private_key_path is ~/.oci/<your_name>-oracle-cloud.pem, the public one is ~/.oci/<your_name>-oracle-cloud_public.pem?
Because if it is so I tried and instance pools are never created.  In Instances Pool > Work requests, Create instances in pool is Failed, with error `Instance launch failed. Error returned by LaunchInstanceConfiguration operation in ComputeManagement service.(400, InvalidParameter, false) Error returned by LaunchInstance operation in Compute service.(400, InvalidParameter, false) Invalid ssh public key type "-----BEGIN" (opc-request-id:....(big error)`
And the key pairs were made using [official documentation](https://docs.oracle.com/en-us/iaas/developer-tutorials/tutorials/tf-provider/01-summary.htm):  
 `openssl genrsa -out $HOME/.oci/<your-rsa-key-name>.pem 2048`  
`chmod 600 $HOME/.oci/<your-rsa-key-name>.pem`  
`openssl rsa -pubout -in $HOME/.oci/<your-rsa-key-name>.pem -out $HOME/.oci/<your-rsa-key-name>_public.pem`

**Comment by NoeSamaille** [comment]
> 

@liviux I just changed input var name from `PATH_TO_PUBLIC_KEY` to `public_key_path` to respect naming standards, but the public key path should be your workstation standard SSH key like `~/.ssh/id_rsa.pub`, it's going to be fed into the VMs so you can access them from your workstation.

**Comment by liviux** [comment]
> @liviux I just changed input var name from `PATH_TO_PUBLIC_KEY` to `public_key_path` to respect naming standards, but the public key path should be your workstation standard SSH key like `~/.ssh/id_rsa.pub`, it's going to be fed into the VMs so you can access them from your workstation.

Yep, that was it. Thanks for your help. Maybe README should be updated with this info so others won't be make the same mistake

**Comment by NoeSamaille** [comment]
> Yep, that was it. Thanks for your help. Maybe README should be updated with this info so others won't be make the same mistake

Sure I'll add a note in the README and also make sure in `example/` folder that  `public_key_path` var defaults to `~/.ssh/id_rsa.pub`. @garutilorenzo I'm going to send a PR shortly

**Pull request merged**
